name: Android CI/CD

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create empty .env file
        run: touch .env

      - name: Generar Keystore temporal
        run: |
          keytool -genkey -v -keystore app/keystore.jks \
            -alias release_key -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "ProdSecurePass2026" -keypass "ProdSecurePass2026" \
            -dname "CN=FabiDownloader, O=Fabi, C=VE"

      - name: Build Release APK
        env:
          KEYSTORE_PATH: "keystore.jks"
          STORE_PASSWORD: "ProdSecurePass2026"
          KEY_ALIAS: "release_key"
          KEY_PASSWORD: "ProdSecurePass2026"
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk

      - name: Get Version
        id: get_version
        run: echo "VERSION=$(cat VERSION | tr -d '\r\n')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('build-{0}-{1}', github.run_number, github.sha) }}
          name: "${{ steps.get_version.outputs.VERSION }} FabiDownloader"
          body: |
            Release generada automáticamente en cada push.
            Rama/Etiqueta: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
